### ISSUE TITLE
jansi-64-1.8.dll problem with multi threaded testing

### ISSUE THREAD

**Issue by karlkilden** [fusesource/jansi#28] opened 2014-05-20 10:49 UTC
Hello,

Using log4j2 I get this problem when I boot multiple Java EE containers during testing:

https://gist.github.com/karlkilden/51aa15ef7be9a1baae94

cheers

**Comment by gnodet** [comment] 2023-09-28 08:03
`Native Library C:\Users\karkil\AppData\Local\Temp\jansi-64-1.8.dll already loaded in another classloader`

Another version of Jansi is already loaded.  Loading the same library in two different versions is not supported by the JVM.
This may be related or even a duplicate of #181 .

**Closed by gnodet** 2023-09-28 08:03 UTC
