### ISSUE TITLE
Not deleted temporary files 

### ISSUE THREAD

**Issue by gkraser** [fusesource/jansi#49] opened 2016-05-04 04:18 UTC
Not deleted temporary files.

OS: Windows 7 SP1 64bit
Java: 1.8.0_72 (32bit)

Code example:

```
import org.fusesource.jansi.*;

public class Main1 {

    public static void main(String[] args) {
        AnsiConsole.systemInstall();
        AnsiConsole.systemUninstall();
    }

}
```

After each run are in the temporary directory files:

for version 1.12 (random suffix):
jansi-32-1-5182090246026316314.12
jansi-32-1-6703096614032337174.12

for version 1.11 (random suffix):
jansi-32-1-4927105933400146001.11

for version 1.10:
jansi-32-1.10.dll

for version 1.9:
jansi-32-1.9.dll

**Comment by greeny88** [comment] 2017-03-09 19:46
I just discovered this myself. Is java creating these or would some other process or project have to be using jansi to see this happen? We had a production server fill up with these files in the temp folder and I'm trying to figure out why before it crashes another machine. 

If it matters, all of mine are of the jansi-64-{digits}.dll variety.

**Comment by hboutemy** [comment] 2018-05-12 14:32
see #98

**Comment by gnodet** [comment] 2020-12-01 18:56
Close as duplicate of #98

**Closed by gnodet** 2020-12-01 18:56 UTC
