### ISSUE TITLE
Support for 256 color terminals

### ISSUE THREAD

**Issue by dblevins** [fusesource/jansi#131] opened 2018-08-12 05:53 UTC
The terminal on OSX supports 256 colors.  It would be awesome if Jansi could know when to strip them out and when to leave them.

Try this on an OSX terminal

```
#!/bin/bash

cat > /tmp/termcolors.java <<EOF
public class termcolors {
    public static void main(String[] args) {
        for (int i = 0; i < 256; i++) {
            System.out.printf("\033[38;5;%sm#@%03d", i, i);
            System.out.print("  ");

            if (i % 12 == 0) System.out.println();
        }
        System.out.println();
    }
}
EOF
javac /tmp/termcolors.java &&
java -cp /tmp termcolors

cat <<EOF

#!/bin/bash
N=202
echo -e "\033[38;5;\${N}mTry Me\033[0m"
EOF


```

**Comment by monitorjbl** [comment] 2018-11-26 01:10
IMO, this would be best served by allowing users to at least extend the existing colors. Right now, the `Color` enum is the roadblock to this; you can't extend an enum in Java and the `fg()/bg()` functions only accept the enum so the stock set of colors is all you get.

It would be pretty trivial to switch that over to an interface that `Color` can then implement. Users could then define custom colors for terminals that support it.

**Comment by dialex** [comment] 2020-07-05 14:32
@dblevins Sorry it took 2 years, but if you're willing to switch from JAnsi to JColor, they you will be happy to know we support not only 256 colors (8-bit) but the whole RGB range. It was fixed by https://github.com/dialex/JColor/issues/27 and just released [(v5.0.0)](https://github.com/dialex/JColor/releases/tag/v5.0.0).

The syntax looks like this:

```java
import static com.diogonunes.jcolor.Ansi.colorize;
import static com.diogonunes.jcolor.Attribute.*;

// Use Case 6: we support 8-bit colors
System.out.print(colorize("We support 8-bit colors (0-255)", TEXT_COLOR(225));

// Use Case 7: we support TrueColors (RGB)
System.out.print(colorize("We support 8-bit colors (0-255)", TEXT_COLOR(15, 251, 23));
```

**Comment by alexandrage** [comment] 2020-11-20 04:46
@dialex JColor doesn't work.

**Comment by dialex** [comment] 2020-11-20 14:33
Can you be more precise regarding what doesn't work, ie. actual vs expected behaviour? Feel free to open an issue.

**Comment by gnodet** [comment] 2020-12-01 16:54
This is implemented in [JLine](https://github.com/jline/jline3) too using the [`AttributedCharSequence`](https://github.com/jline/jline3/blob/master/terminal/src/main/java/org/jline/utils/AttributedCharSequence.java) and related classes (`AttributedString`, `AttributedStringBuilder`, etc...)

**Comment by gnodet** [comment] 2020-12-03 12:49
I'm going to back port the JLine classes to Jansi with additional support for TrueColors terminals.

**Comment by gnodet** [comment] 2020-12-15 09:55
Done as part of 2.1.0.

**Closed by gnodet** 2020-12-15 09:55 UTC

**Comment by terheyden** [comment] 2022-10-04 21:52
Works great, here's a test method for folks:

```java
public static void testJAnsi() {

    Ansi ansi = Ansi.ansi();

    for (int index = 0; index < 256; index++) {
        ansi.fg(index).a("FG %d ".formatted(index));
    }

    AnsiConsole.out().println(ansi);

    ansi = Ansi.ansi();

    for (int index = 0; index < 256; index++) {
        ansi.bg(index).a("BG %d ".formatted(index));
    }

    AnsiConsole.out().println(ansi);
}
```
