### ISSUE TITLE
1.6 version range broken - jansi 1.6.1 patch needed

### ISSUE THREAD

**Issue by DivineThreepwood** [fusesource/jansi#103] opened 2018-02-05 16:55 UTC
Dear Fusesource,

since last Friday nearly all my software releases (released within the last years) are broken because of a jansi upstream dependency issue. I have no idea what exactly happend last Friday but i would be totally happy if you can support me by solving the issue.

The issue: All releases of my github organisation are using the project "jps" which is a simple command line parser (https://github.com/openbase/jps). This project has the following dependency declaration linking to jansi:
```xml
        <dependency>
            <groupId>org.fusesource.jansi</groupId>
            <artifactId>jansi</artifactId>
            <version>[1.6,1.7)</version>
        </dependency>
```
Don't get me wrong, I will definitely use you latest version 1-7 in future releases but since Friday all releases of my organization released within the last 2 years are not compiling anymore because of the following error:
```
[ERROR] Failed to execute goal on project jps: 
Could not resolve dependencies for project org.openbase:jps:jar:3.2.11: 
Failed to collect dependencies for [org.fusesource.jansi:jansi:jar:[1.6,1.7) (compile), ch.qos.logback:logback-classic:jar:[1.2,1.3-alpha) (compile), commons-io:commons-io:jar:[2.5,2.6-alpha) (compile), junit:junit:jar:[4.12,4.13-alpha) (test)]: 
No versions available for org.fusesource.jansi:jansi:jar:[1.6,1.7) within specified range -> [Help 1]
```

After investigating some hours i found out that the range
```<jansi.version>[1.6,1.12)</jansi.version>``` 
is still not working but since 1.13 is included it works again
```<jansi.version>[1.6,1.13)</jansi.version>```

here is a minimal pom reproducing the issue:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>org</groupId>
    <artifactId>test</artifactId>
    <version>1.0-SNAPSHOT</version>
    <name>JansiRangeTest</name>
    <packaging>jar</packaging>
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.7.0</version>
            </plugin>
        </plugins>
    </build>
    <dependencies>
        <dependency>
            <groupId>org.fusesource.jansi</groupId>
            <artifactId>jansi</artifactId>
            <version>[1.6,1.7)</version>         <!-- needed -->
            <!--version>[1,1.12)</version-->     <!-- broken -->
            <!--version>[1,1.13)</version-->     <!-- working -->
        </dependency>
    </dependencies>
</project>
```

which can be compiled with <pre>mvn clean install -Dmaven.javadoc.skip=true</pre> (by the way your javadoc is broken with java 1.8)

I already tried to compile jansi 1.6 by myself but without any luck because of dependency issues. This is maybe the reason why maven is just skipping the dependency in the range declaration because upstream dependencies can not be resolved.

Could you maybe fix the dependency issue of jansi 1.6 and release a patched version 1.6.1 ?

**Comment by slachiewicz** [comment] 2018-03-02 21:50
Maybe the reason is that in file http://central.maven.org/maven2/org/fusesource/jansi/jansi/maven-metadata.xml there is only

```
<metadata>
<groupId>org.fusesource.jansi</groupId>
<artifactId>jansi</artifactId>
<versioning>
<latest>1.17</latest>
<release>1.17</release>
<versions>
<version>1.12</version>
<version>1.13</version>
<version>1.14</version>
<version>1.15</version>
<version>1.16</version>
<version>1.17</version>
</versions>
<lastUpdated>20180202105630</lastUpdated>
</versioning>
</metadata>
```
Maybe maven-metadata needs to be regenerated?

(we fixed javadoc problems few days ago)

**Comment by DivineThreepwood** [comment] 2018-03-05 15:03
> Maybe maven-metadata needs to be regenerated?
This actually happens if new versions are deployed. Maybe the generator was broken or some file server downtime while performing the 1.17 release?  You could try to release 1.6.1. and check if the versions are fully listed afterwards. Or just contract the Sonatype team and ask why your project versions are missing?

**Comment by hboutemy** [comment] 2018-03-05 18:46
I'll see with @gnodet if he can update his local maven-metadata.xml with full list of versions before releasing.
Notice: you should not use version ranges, this is gives non reproducible result and complex situation where fixed version would be much better

**Comment by gnodet** [comment] 2018-03-05 23:35
I don't think it works this way.
When you stage a release, a maven metadata is uploaded with only the uploaded version.  It's then merged when the staging repository is merged.
I have no way to do that by hacking my maven metadata.  
I think the problem should be raised with the Sonatype team to fix it.

**Comment by hboutemy** [comment] 2018-04-15 11:47
issue created: https://issues.sonatype.org/browse/MVNCENTRAL-3323

**Comment by hboutemy** [comment] 2018-04-16 21:43
issue fixed: maven-metadata.xml has been regenerated with every available version
the issue seems to remain private, but its content is equivalent to https://issues.sonatype.org/browse/MVNCENTRAL-1356

**Closed by hboutemy** 2018-04-16 21:43 UTC

**Comment by DivineThreepwood** [comment] 2018-04-18 23:03
Hey, I can confirm that the desired versions are available again. My old releases downloading the jansi dependency again from the central maven repo without any issues.

Thanks a lot for your investigation!
